version: "3.0"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-08-29T23-07-35Z
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - default
    volumes:
      - ./minio/data1:/data1
      - ./minio/data2:/data2
    command: server --console-address ":9001"  http://minio/data{1...2}
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=vagrant
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    restart: always
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

