version: "2.1"

services:
  clickhouse:
    image: bitnami/clickhouse:24-debian-12
    environment:
      - CLICKHOUSE_ADMIN_PASSWORD=${CLICKHOUSE_ADMIN_PASSWORD}
      - CLICKHOUSE_ADMIN_USER=${CLICKHOUSE_ADMIN_USER}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    volumes:
      - ./data:/bitnami/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    restart: always

    
